config/routes.rb
    controllers authorizations: 'oauth/authorizations',
                authorized_applications: 'oauth/authorized_applications',
                tokens: 'oauth/tokens'
  end

  get '.well-known/change-password', to: redirect('/auth/edit')

  get 'manifest', to: 'manifests#show', defaults: { format: 'json' }

  devise_scope :user do
    match '/auth/finish_signup' => 'auth/confirmations#finish_signup', via: [:get, :patch], as: :finish_signup
  end

  devise_for :users, path: 'auth', controllers: {
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations',
  }

  namespace :settings do
    resource :profile, only: [:show, :update]
    resource :preferences, only: [:show, :update]
    resource :notifications, only: [:show, :update]

    namespace :billing do
      get :upgrade, to: 'upgrade#index', as: :upgrade
      get :transactions, to: 'transactions#index', as: :transactions
      post '/btcpay-notification', to: 'upgrade#btcpay_notification', as: :btcpay_notification
    end

    namespace :verifications do
      get :moderation, to: 'moderation#index', as: :moderation
      get 'moderation/:id/approve', to: 'moderation#approve', as: :approve
      get 'moderation/:id/reject', to: 'moderation#reject', as: :reject

      resources :requests, only: [:index, :create]
    end

    resource :export, only: [:show, :create]
    namespace :exports, constraints: { format: :csv } do
      resources :follows, only: :index, controller: :following_accounts
      resources :blocks, only: :index, controller: :blocked_accounts
      resources :mutes, only: :index, controller: :muted_accounts
      resources :lists, only: :index, controller: :lists
    end

    resource :two_factor_authentication, only: [:show, :create, :destroy]
    namespace :two_factor_authentication do
      resources :recovery_codes, only: [:create]
      resource :confirmation, only: [:new, :create]
    end

    resources :applications, except: [:edit] do
      member do
        post :regenerate
      end
    end

    resource :delete, only: [:show, :destroy]

    resources :sessions, only: [:destroy]
    resources :scheduled_statuses, only: [:index, :destroy]
    resources :filters, except: [:show]
  end

  resources :media, only: [:show] do
    get :player
  end

  get '/media_proxy/:id/(*any)', to: 'media_proxy#show', as: :media_proxy

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :email_domain_blocks, only: [:index, :new, :create, :destroy]
    resources :link_blocks, only: [:index, :new, :create, :destroy]
    resources :statuses, only: [:index, :show, :create, :update, :destroy]
    resources :preview_cards, only: [:index, :create, :destroy]
    # resources :chat_messages, only: [:index, :destroy]
    resources :action_logs, only: [:index]
    resources :warning_presets, except: [:new]
    resource :settings, only: [:edit, :update]
    resources :promotions, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :expenses, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :group_categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :trending_hashtags, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :reports, only: [:index, :show] do
      member do
        post :assign_to_self
        post :unassign
        post :reopen
        post :resolve
      end

      resources :reported_statuses, only: [:create]
    end

    resources :report_notes, only: [:create, :destroy]

    resources :accounts, only: [:index, :show, :edit, :update] do
      member do
        post :enable
        post :unsilence
        post :unsuspend
        post :redownload
        post :remove_avatar
        post :remove_header
        post :memorialize
        post :approve
        post :reject
        post :verify
        post :unverify
        post :add_donor_badge
        post :remove_donor_badge
        post :add_investor_badge
        post :remove_investor_badge
        post :reset_spam
        get :edit_pro
        put :save_pro
      end

      resource :change_email, only: [:show, :update]
      resource :reset, only: [:create]
      resource :action, only: [:new, :create], controller: 'account_actions'
      resources :account_statuses, only: [:index, :show, :create, :update, :destroy]
      resources :followers, only: [:index]
      resources :follows, only: [:index]
      resources :joined_groups, only: [:index]
      resources :chat_conversation_accounts, only: [:index]
      resources :chat_messages, only: [:index, :show, :create, :update, :destroy]

      resource :confirmation, only: [:create] do
        collection do
          post :resend
        end
      end

      resource :role do
        member do
          post :promote
          post :demote
        end
      end
    end

    resources :users, only: [] do
      resource :two_factor_authentication, only: [:destroy]
    end

    resources :custom_emojis, only: [:index, :new, :create, :update, :destroy]

    resources :groups, only: [:index, :show, :update, :destroy] do
      member do
        post :make_me_admin
      end
    end

    resources :account_moderation_notes, only: [:create, :destroy]
  end

  namespace :api do
    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # Ads
    post '/ad_click', to: 'ads#click'
    post '/ad_view', to: 'ads#view'

    # Identity proofs
    get :proofs, to: 'proofs#index'

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :update, :show, :destroy] do
        scope module: :statuses do
          resources :reblogged_by, controller: :reblogged_by_accounts, only: :index
          resources :favourited_by, controller: :favourited_by_accounts, only: :index
          resource :reblog, only: :create
          post :unreblog, to: 'reblogs#destroy'

          resource :favourite, only: :create
          post :unfavourite, to: 'favourites#destroy'

          resource :bookmark, only: [:show, :create]
          post :unbookmark, to: 'bookmarks#destroy'

          resource :pin, only: [:show, :create]
          post :unpin, to: 'pins#destroy'
        end

        member do
          get :comments
          get :context
          get :card
          get :revisions
        end
      end

      resources :hmac_tokens, only: [:create]

      namespace :timelines do
        resource :home, only: :show, controller: :home
        resource :pro, only: :show, controller: :pro
        resources :tag, only: :show
        resources :list, only: :show
        resources :group, only: :show
        resources :group_collection, only: :show
        resources :group_pins, only: :show
        resources :preview_card, only: :show
        resource :explore, only: :show, controller: :explore
      end

      namespace :chat_conversation_accounts do
        
      end

      resources :chat_conversation_accounts, only: :show do
        member do
          post :messenger_block_relationships
          post :block_messenger
          post :unblock_messenger
          post :mute_chat_conversation
          post :unmute_chat_conversation
          post :pin_chat_conversation
          post :unpin_chat_conversation
          post :leave_group_chat_conversation
        end
      end

      namespace :chat_conversations do
        resources :messages, only: :show do
          member do
            delete :destroy_all
          end
        end
        resources :approved_conversations, only: :index do
          collection do
            get :unread_count
            post :reset_all_unread_count
          end
        end
        resources :requested_conversations, only: :index do
          collection do
            get :count
          end
        end
        resources :blocked_chat_accounts, only: :index
        resources :muted_conversations, only: :index
        resources :search_conversations, only: :index
      end

      resources :chat_conversation, only: [:show, :create] do
        member do
          post :mark_chat_conversation_approved
          post :mark_chat_conversation_read
          post :mark_chat_conversation_hidden
          post :set_expiration_policy
        end
      end

      resources :links,         only: :show
      resources :hashtags,         only: :show
      resource :popular_links,  only: :show
      resources :streaming,     only: [:index]
      resources :custom_emojis, only: [:index]
      resources :suggestions,   only: [:index, :destroy]
      resources :scheduled_statuses, only: [:index, :show, :update, :destroy]
      resources :preferences,   only: [:index]
      resources :group_categories, only: [:index]
      resources :chat_messages, only: [:create, :destroy]
      resources :promotions,   only: [:index]
      resources :follows,      only: [:create]
      resources :media,        only: [:create, :update]
      resources :blocks,       only: [:index]
      resources :mutes,        only: [:index]
      resources :blockedby,    only: [:index]
      resources :favourites,   only: [:index]
      resources :reports,      only: [:create]
      resources :filters,      only: [:index, :create, :show, :update, :destroy]
      resources :shortcuts,    only: [:index, :create, :show, :destroy]
      resources :albums,       only: [:create, :update, :show, :destroy]
      resources :album_lists,  only: [:show]
      resource :trending_hashtags,  only: [:show]
      resource :expenses,     only: [:show]
      resources :comments,    only: [:show]

      resources :bookmark_collections, only: [:index, :create, :show, :update, :destroy] do
        resources :bookmarks, only: [:index], controller: 'bookmark_collections/bookmarks'
        member do
          post :update_status
        end
      end

      get '/account_by_username/:username', to: 'account_by_username#show', username: username_regex

app/models/tag.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: tags
#
#  id         :bigint(8)        not null, primary key
#  name       :string           default(""), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord
  has_and_belongs_to_many :statuses
  has_and_belongs_to_many :accounts
  has_and_belongs_to_many :sample_accounts, -> { searchable.discoverable.popular.limit(3) }, class_name: 'Account'

  has_one :account_tag_stat, dependent: :destroy

  HASHTAG_NAME_RE = '[[:word:]_]*[[:alpha:]_·][[:word:]_]*'
  HASHTAG_RE = /(?:^|[^\/\)\w])#(#{HASHTAG_NAME_RE})/i.freeze
  CASHTAG_RE = /(?:^|[^\/\)\w])\$([a-zA-Z]{1,})/.freeze
  G_TAG_RE = /(?:^|[^\/\)\w])g\/([a-zA-Z]{1,})/.freeze

  validates :name, presence: true, uniqueness: true, format: { with: /\A#{HASHTAG_NAME_RE}\z/i }

  scope :discoverable, -> { joins(:account_tag_stat).where(AccountTagStat.arel_table[:accounts_count].gt(0)).where(account_tag_stats: { hidden: false }).order(Arel.sql('account_tag_stats.accounts_count desc')) }
  scope :hidden, -> { where(account_tag_stats: { hidden: true }) }
  scope :most_used, ->(account) { joins(:statuses).where(statuses: { account: account }).group(:id).order(Arel.sql('count(*) desc')) }

  delegate :accounts_count,
           :accounts_count=,
           :increment_count!,
           :decrement_count!,
           :hidden?,
           to: :account_tag_stat

  after_save :save_account_tag_stat

  def account_tag_stat
    super || build_account_tag_stat
  end

  def cached_sample_accounts
    Rails.cache.fetch("#{cache_key}/sample_accounts", expires_in: 12.hours) { sample_accounts }
  end

  def to_param
    name
  end

  def history
    days = []

    7.times do |i|
      day = i.days.ago.beginning_of_day.to_i

      days << {
        day: day.to_s,
        uses: Redis.current.with do |conn|
          conn.get("activity:tags:#{id}:#{day}") || '0'
        end,
        accounts: Redis.current.with do |conn|
          conn.pfcount("activity:tags:#{id}:#{day}:accounts").to_s
        end,
      }
    end

    days
  end

  class << self
    def search_for(term, offset = 0)
      Tag.matching(:name, :starts_with, term)
         .order(:name)
         .limit(25)
         .offset(offset)
    end

    def find_normalized(name)
      find_by(name: name.mb_chars.downcase.to_s)
    end

    def find_normalized!(name)
      find_normalized(name) || raise(ActiveRecord::RecordNotFound)
    end
  end

  private

  def save_account_tag_stat
    return unless account_tag_stat&.changed?
    account_tag_stat.save
  end
end

app/controllers/admin/reports_controller.rb
# frozen_string_literal: true

module Admin
  class ReportsController < BaseController
    before_action :set_report, except: [:index]

    def index
      authorize :report, :index?
      @reports = filtered_reports.page(params[:page])
      @categories = ReportFilter.new(filter_params.except(:category)).results.order('category nulls first').group(:category).count
    end

    def show
      authorize @report, :show?

      @report_note  = @report.notes.new
      @report_notes = (@report.notes.latest + @report.history + @report.target_account.targeted_account_warnings.latest.custom).sort_by(&:created_at)
      @form         = Form::StatusBatch.new
    end

    def assign_to_self
      authorize @report, :update?
      @report.update!(assigned_account_id: current_account.id)
      log_action :assigned_to_self, @report
      redirect_to admin_report_path(@report)
    end

    def unassign
      authorize @report, :update?
      @report.update!(assigned_account_id: nil)
      log_action :unassigned, @report
      redirect_to admin_report_path(@report)
    end

    def reopen
      authorize @report, :update?
      @report.unresolve!
      log_action :reopen, @report
      redirect_to admin_report_path(@report)
    end

    def resolve
      authorize @report, :update?
      @report.resolve!(current_account)
      log_action :resolve, @report
      redirect_to admin_reports_path, notice: I18n.t('admin.reports.resolved_msg')
    end

    private

    def filtered_reports
      ReportFilter.new(filter_params).results.order(id: :desc).includes(:account, :target_account)
    end

    def filter_params
      params.permit(
        :account_id,
        :resolved,
        :comment,
        :target_account_id,
        :category
      )
    end

    def set_report
      @report = Report.find(params[:id])
    end
  end
end

app/controllers/api/v1/reports_controller.rb
# frozen_string_literal: true

class Api::V1::ReportsController < Api::BaseController
  before_action -> { doorkeeper_authorize! :write, :'write:reports' }, only: [:create]
  before_action :require_user!

  def create
    @report = ReportService.new.call(
      current_account,
      reported_account,
      status_ids: reported_status_ids,
      comment: report_params[:comment],
      forward: report_params[:forward],
      category: report_params[:category]
    )

    render json: @report, serializer: REST::ReportSerializer
  end

  private

  def reported_status_ids
    reported_account.statuses.find(status_ids).pluck(:id)
  end

  def status_ids
    Array(report_params[:status_ids])
  end

  def reported_account
    Account.find(report_params[:account_id])
  end

  def report_params
    params.permit(:account_id, :comment, :forward, :category, status_ids: [])
  end
end

app/views/admin/reports/_action_log.html.haml
.speech-bubble.positive
  .speech-bubble__bubble
    = t("admin.action_logs.actions.#{action_log.action}_#{action_log.target_type.underscore}", name: content_tag(:span, action_log.account.username, class: 'username'), target: content_tag(:span, log_target(action_log), class: 'target')).html_safe
  .speech-bubble__owner
    = admin_account_link_to(action_log.account)
    %time.formatted{ datetime: action_log.created_at.iso8601 }= l action_log.created_at

app/views/admin/reports/_status.html.haml
.batch-table__row
  %label.batch-table__row__select.batch-checkbox
    = f.check_box :status_ids, { multiple: true, include_hidden: false }, status.id
  .batch-table__row__content
    .status__content><
      - if status.proper.spoiler_text.blank?
        = Formatter.instance.plaintext(status.proper)
      - else
        %details<
          %summary><
            %strong> Content warning: #{Formatter.instance.format_spoiler(status.proper)}
          = Formatter.instance.plaintext(status.proper)

    - unless status.proper.media_attachments.empty?
      - if status.proper.media_attachments.first.video?
        - video = status.proper.media_attachments.first
        = react_component :video, src: video.file.url(:original), preview: video.file.url(:small), sensitive: !current_account&.user&.show_all_media? && status.proper.sensitive? || current_account&.user&.hide_all_media?, width: 610, height: 343, inline: true, alt: video.description
      - else
        = react_component :media_gallery, height: 343, sensitive: !current_account&.user&.show_all_media? && status.sensitive? || current_account&.user&.hide_all_media?, 'autoPlayGif': current_account&.user&.setting_auto_play_gif, media: status.proper.media_attachments.map { |a| ActiveModelSerializers::SerializableResource.new(a, serializer: REST::MediaAttachmentSerializer).as_json }

    .detailed-status__meta
      = link_to TagManager.instance.url_for(status), class: 'detailed-status__datetime', target: stream_link_target, rel: 'noopener' do
        %time.formatted{ datetime: status.created_at.iso8601, title: l(status.created_at) }= l(status.created_at)
      ·
      - if status.reblog?
        = fa_icon('retweet fw')
        = t('statuses.boosted_from_html', acct_link: admin_account_inline_link_to(status.proper.account))
      - else
        = fa_visibility_icon(status)
        = t("statuses.visibilities.#{status.visibility}")
      - if status.proper.sensitive?
        ·
        = fa_icon('eye-slash fw')
        = t('stream_entries.sensitive_content')
      - if !status.group_id.nil?
        ·
        %a{href: "/groups/#{status.group_id}", style: "color:#757575;text-decoration:none;font-size:14px;"}= status.group.title

app/views/admin/reports/index.html.haml
- content_for :page_title do
  = t('admin.reports.title')
  = "(#{@reports.length})"

.filters
  .filter-subset
    %strong= t('admin.reports.status')
    %ul
      %li= filter_link_to t('admin.reports.unresolved'), resolved: nil
      %li= filter_link_to t('admin.reports.resolved'), resolved: '1'

- if @categories.present?
  .filters
    .filter-subset
      %strong= 'Categories'
      %ul
        %li= filter_link_to 'All', category: nil
        - @categories.each do |(category, count)|
          %li= filter_link_to "#{category || 'Not Specified'} (#{count})", category: category || ''

= form_tag admin_reports_url, method: 'GET', class: 'simple_form' do
  .fields-group
    .input.string.optional
      = text_field_tag :comment, params[:comment], class: 'string optional', placeholder: "Comment"

    .actions
      %button= t('admin.accounts.search')
      = link_to t('admin.accounts.reset'), admin_reports_path, class: 'button negative'

- @reports.group_by(&:target_account_id).each do |target_account_id, reports|
  - target_account = reports.first.target_account
  .report-card
    .report-card__profile
      = account_link_to target_account, '', size: 36, path: admin_account_path(target_account.id)
      .report-card__profile__stats
        %div{ :style => "display:flex;flex-direction:row;margin-bottom:4px;" }
          - if target_account.is_spam?
            %span{ :style => "display:inline-block;margin-right:4px;font-size:12px;background-color:#781600;border-radius:6px;color:#fff;width:40px;line-height:22px;font-weight:600;text-align:center;padding:2px 0 0 6px;" } SPAM
          - if target_account.is_pro
            %span{ :style => "display:inline-block;margin-right:4px;font-size:12px;background-color:#FFD700;border-radius:6px;color:#292929;width:24px;line-height:22px;font-weight:600;text-align:center;padding:2px 0 0 2px;" } P
          - if target_account.is_verified
            %span{ :style => "display:inline-block;margin-right:4px;font-size:12px;background-color:#fff;border-radius:6px;color:#292929;width:24px;line-height:22px;font-weight:600;text-align:center;padding:2px 0 0 2px;" } V
          - if target_account.is_donor
            %span{ :style => "display:inline-block;margin-right:4px;font-size:12px;background-color:#4EA6FF;border-radius:6px;color:#292929;width:24px;line-height:22px;font-weight:600;text-align:center;padding:2px 0 0 2px;" } D
          - if target_account.is_investor
            %span{ :style => "display:inline-block;font-size:12px;background-color:#6DD900;border-radius:6px;color:#292929;width:24px;line-height:22px;font-weight:600;text-align:center;padding:2px 0 0 2px;" } I
        - if target_account.suspended?
          %span.red= t('admin.accounts.suspended')
        - elsif target_account.silenced?
          %span.red= t('admin.accounts.silenced')
        - elsif target_account.user&.disabled?
          %span.red= t('admin.accounts.disabled')
        - else
          %span.neutral= t('admin.accounts.no_limits_imposed')
    .report-card__summary
      - reports.each do |report|
        = link_to admin_report_path(report), class: "report-card__summary__item", style: "text-decoration:none;text-decoration: none;padding:10px;color: #999;font-size:15px;" do
          .report-card__summary__item__reported-by{style: "padding: 10px 0 0 0;"}
            - if report.account.local?
              = admin_account_basic report.account
            - else
              = report.account.domain
          .report-card__summary__item__content{style: "max-width: calc(100% - 370px)!important;"}
            .one-line= report.comment.presence || t('admin.reports.comment.none')

            %span.report-card__summary__item__content__icon{ title: t('admin.accounts.statuses') }
              = fa_icon('comment')
              = report.statuses.count

            %span.report-card__summary__item__content__icon{ title: t('admin.accounts.media_attachments') }
              = fa_icon('camera')
              = report.media_attachments.count

            %span.report-card__summary__item__content__icon{ title: 'Category' }
              - if report.category.present?
                = fa_icon('tag')
                = report.category

          .report-card__summary__item__assigned.hidden-sm{style: "width:220px;text-align:right;padding: 10px 0 0 0;"}
            %time.formatted{ datetime: report.created_at.iso8601 }
= paginate @reports

app/views/admin/reports/show.html.haml
- content_for :header_tags do
  = javascript_pack_tag 'admin', integrity: true, async: true, crossorigin: 'anonymous'

- content_for :page_title do
  = t('admin.reports.report', id: @report.id)

%div{ style: 'overflow: hidden; margin-bottom: 20px' }
  - if @report.unresolved?
    %div{ style: 'float: right' }
      - if @report.target_account.local?
        = link_to t('admin.accounts.warn'), new_admin_account_action_path(@report.target_account_id, type: 'none', report_id: @report.id), class: 'button'
        = link_to t('admin.accounts.disable'), new_admin_account_action_path(@report.target_account_id, type: 'disable', report_id: @report.id), class: 'button button--destructive'
      = link_to t('admin.accounts.silence'), new_admin_account_action_path(@report.target_account_id, type: 'silence', report_id: @report.id), class: 'button button--destructive'
      - if !@report.target_account.is_pro? && !@report.target_account.is_investor? && !@report.target_account.is_donor? && !@report.target_account.is_verified?
        = link_to t('admin.accounts.perform_full_suspension'), new_admin_account_action_path(@report.target_account_id, type: 'suspend', report_id: @report.id), class: 'button button--destructive'
    %div{ style: 'float: left' }
      = link_to t('admin.reports.mark_as_resolved'), resolve_admin_report_path(@report), method: :post, class: 'button'
  - else
    = link_to t('admin.reports.mark_as_unresolved'), reopen_admin_report_path(@report), method: :post, class: 'button'

%hr.spacer

.table-wrapper
  %table.table.inline-table
    %tbody
      %tr
        %th= t('admin.reports.reported_account')
        %td= admin_account_link_to @report.target_account
        %td= table_link_to 'flag', pluralize(@report.target_account.targeted_reports.count, t('admin.reports.account.report')), admin_reports_path(target_account_id: @report.target_account.id)
        %td= render 'admin/accounts/account_flags_block', :account => @report.target_account
      %tr
        %th= t('admin.reports.reported_by')
        - if @report.account.local?
          %td= admin_account_link_to @report.account
          %td= table_link_to 'flag', pluralize(@report.account.targeted_reports.count, t('admin.reports.account.report')), admin_reports_path(target_account_id: @report.account.id)
          %td= render 'admin/accounts/account_flags_block', :account => @report.account
        - else
          %td{ colspan: 3 }= @report.account.domain
      %tr
        %th= t('admin.reports.created_at')
        %td{ colspan: 3 }
          %time.formatted{ datetime: @report.created_at.iso8601 }
      %tr
        %th= t('admin.reports.updated_at')
        %td{ colspan: 3 }
          %time.formatted{ datetime: @report.updated_at.iso8601 }
      %tr
        %th= t('admin.reports.status')
        %td
          - if @report.action_taken?
            = t('admin.reports.resolved')
          - else
            = t('admin.reports.unresolved')
        %td{ colspan: 2 }
          - if @report.action_taken?
            = table_link_to 'envelope-open', t('admin.reports.reopen'), admin_report_path(@report, outcome: 'reopen'), method: :put
      - if !@report.action_taken_by_account.nil?
        %tr
          %th= t('admin.reports.action_taken_by')
          %td{ colspan: 3 }
            = admin_account_link_to @report.action_taken_by_account
      - else
        %tr
          %th= t('admin.reports.assigned')
          %td
            - if @report.assigned_account.nil?
              \-
            - else
              = admin_account_link_to @report.assigned_account
          %td
            - if @report.assigned_account != current_user.account
              = table_link_to 'user', t('admin.reports.assign_to_self'), assign_to_self_admin_report_path(@report), method: :post
          %td
            - if !@report.assigned_account.nil?
              = table_link_to 'trash', t('admin.reports.unassign'), unassign_admin_report_path(@report), method: :post

%hr.spacer

.speech-bubble
  .speech-bubble__bubble= simple_format(@report.comment.presence || t('admin.reports.comment.none'))
  .speech-bubble__owner
    - if @report.account.local?
      = admin_account_link_to @report.account
    - else
      = @report.account.domain
      %br/
    %time.formatted{ datetime: @report.created_at.iso8601 }

- unless @report.statuses.empty?
  %hr.spacer/

  = form_for(@form, url: admin_report_reported_statuses_path(@report.id)) do |f|
    .batch-table
      .batch-table__toolbar
        %label.batch-table__toolbar__select.batch-checkbox-all
          = check_box_tag :batch_checkbox_all, nil, false
        .batch-table__toolbar__actions
          = f.button safe_join([fa_icon('eye-slash'), t('admin.statuses.batch.nsfw_on')]), name: :nsfw_on, class: 'table-action-link', type: :submit, data: { confirm: t('admin.reports.are_you_sure') }
          = f.button safe_join([fa_icon('eye'), t('admin.statuses.batch.nsfw_off')]), name: :nsfw_off, class: 'table-action-link', type: :submit, data: { confirm: t('admin.reports.are_you_sure') }
          = f.button safe_join([fa_icon('trash'), t('admin.statuses.batch.delete')]), name: :delete, class: 'table-action-link', type: :submit, data: { confirm: t('admin.reports.are_you_sure') }
      .batch-table__body
        = render partial: 'admin/reports/status', collection: @report.statuses, locals: { f: f }

%hr.spacer/

- @report_notes.each do |item|
  - if item.is_a?(Admin::ActionLog)
    = render partial: 'action_log', locals: { action_log: item }
  - else
    = render item

= simple_form_for @report_note, url: admin_report_notes_path do |f|
  = render 'shared/error_messages', object: @report_note
  = f.input :report_id, as: :hidden

  .field-group
    = f.input :content, placeholder: t('admin.reports.notes.placeholder'), rows: 6

  .actions
    - if @report.unresolved?
      = f.button :button, t('admin.reports.notes.create_and_resolve'), name: :create_and_resolve, type: :submit
    - else
      = f.button :button, t('admin.reports.notes.create_and_unresolve'), name: :create_and_unresolve, type: :submit
    = f.button :button, t('admin.reports.notes.create'), type: :submit